#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2013 - 2015 CERN
# Author: Pawel Szostek (pawel.szostek@cern.ch)
# Multi-tool support by Javier D. Garcia-Lasheras (javier@garcialasheras.com)
#
# This file is part of Hdlmake.
#
# Hdlmake is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hdlmake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Hdlmake.  If not, see <http://www.gnu.org/licenses/>.
#

"""Module providing support for Aldec Active-HDL simulator"""

from hdlmake.action import ActionMakefile
from hdlmake.srcfile import VHDLFile, VerilogFile, SVFile


class ToolActiveHDL(ActionMakefile):

    """Class providing the interface to control an Active-HDL simulation"""

    TOOL_INFO = {
        'name': 'Aldec Active-HDL',
        'id': 'aldec',
        'windows_bin': 'vsimsa',
        'linux_bin': None}

    SUPPORTED_FILES = []

    CLEAN_TARGETS = {'clean': ["run.command", "library.cfg", "work"],
                     'mrproper': ["*.vcd", "*.asdb"]}

    def __init__(self):
        super(ToolActiveHDL, self).__init__()

    def detect_version(self, path):
        """Get the version from the Aldec-HDL binary program"""
        pass

    def makefile_sim_compilation(self, fileset, top_module):
        """Print Makefile compilation target for Aldec Active-HDL simulator"""
        self.writeln("simulation:")
        self.writeln("\t\techo \"# Active-HDL command file,"
                     " generated by HDLMake\" > run.command")
        self.writeln()
        self.writeln("\t\techo \"# Create library and set as"
                     " default target\" >> run.command")
        self.writeln("\t\techo \"alib work\" >> run.command")
        self.writeln("\t\techo \"set worklib work\" >> run.command")
        self.writeln()
        self.writeln(
            "\t\techo \"# Compiling HDL source files\" >> run.command")
        for vl_file in fileset.filter(VerilogFile):
            self.writeln(
                "\t\techo \"alog " +
                vl_file.rel_path(
                ) +
                "\" >> run.command")
        for sv_file in fileset.filter(SVFile):
            self.writeln(
                "\t\techo \"alog " +
                sv_file.rel_path(
                ) +
                "\" >> run.command")
        for vhdl_file in fileset.filter(VHDLFile):
            self.writeln(
                "\t\techo \"acom " +
                vhdl_file.rel_path(
                ) +
                "\" >> run.command")
        self.writeln()
        self.writeln("\t\tvsimsa -do run.command")
